matrix:
  - name: Markdown
    aspell:
      lang: en
      # ignore-case: true
    dictionary:
      encoding: utf-8
      wordlists:
        - .wordlist-md
    pipeline:
      - pyspelling.filters.markdown:
      - pyspelling.filters.html:
          comments: false
          attributes:
          - title
          - alt
          ignores:
          - code
          - pre
    sources:
      - '**/*.md|!venv/**|!containers/s2i-cuda/common/**|!containers/s2i-base/**'
    default_encoding: utf-8
